//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Spoffice.Website.Resources.Views.Account.AccountStrings", typeof(AccountStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        public static string AccountInformation {
            get {
                return ResourceManager.GetString("AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the form below to change your password..
        /// </summary>
        public static string ChangePasswordTip {
            get {
                return ResourceManager.GetString("ChangePasswordTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New passwords are required to be a minimum of {0} characters in length..
        /// </summary>
        public static string ChangePasswordTip2 {
            get {
                return ResourceManager.GetString("ChangePasswordTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some other account content. Possibly showing how many times your favourite songs have been played or something like that..
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password:.
        /// </summary>
        public static string LabelConfirmPassword {
            get {
                return ResourceManager.GetString("LabelConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password:.
        /// </summary>
        public static string LabelCurrentPassword {
            get {
                return ResourceManager.GetString("LabelCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string LabelEmail {
            get {
                return ResourceManager.GetString("LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password:.
        /// </summary>
        public static string LabelNewPassword {
            get {
                return ResourceManager.GetString("LabelNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password:.
        /// </summary>
        public static string LabelNewPasswordConfirm {
            get {
                return ResourceManager.GetString("LabelNewPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string LabelRememberMe {
            get {
                return ResourceManager.GetString("LabelRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string LabelUsername {
            get {
                return ResourceManager.GetString("LabelUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your username and password. {0} if you don&apos;t have an account..
        /// </summary>
        public static string LogOnHint {
            get {
                return ResourceManager.GetString("LogOnHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the form below to create a new account..
        /// </summary>
        public static string RegisterTip {
            get {
                return ResourceManager.GetString("RegisterTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords are required to be a minimum of {0} characters in length..
        /// </summary>
        public static string RegisterTip2 {
            get {
                return ResourceManager.GetString("RegisterTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New Account.
        /// </summary>
        public static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s account.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
