//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Spoffice.Website.App_GlobalResources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A username for that e-mail address already exists. Please enter a different e-mail address..
        /// </summary>
        public static string AccountDuplicateEmail {
            get {
                return ResourceManager.GetString("AccountDuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already exists. Please enter a different user name..
        /// </summary>
        public static string AccountDuplicateUserName {
            get {
                return ResourceManager.GetString("AccountDuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        public static string AccountInformation {
            get {
                return ResourceManager.GetString("AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string AccountInformationEmail {
            get {
                return ResourceManager.GetString("AccountInformationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change account information.
        /// </summary>
        public static string AccountInformationLink {
            get {
                return ResourceManager.GetString("AccountInformationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Account Information.
        /// </summary>
        public static string AccountInformationTitle {
            get {
                return ResourceManager.GetString("AccountInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password retrieval answer provided is invalid. Please check the value and try again..
        /// </summary>
        public static string AccountInvalidAnswer {
            get {
                return ResourceManager.GetString("AccountInvalidAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mail address provided is invalid. Please check the value and try again..
        /// </summary>
        public static string AccountInvalidEmail {
            get {
                return ResourceManager.GetString("AccountInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password provided is invalid. Please enter a valid password value..
        /// </summary>
        public static string AccountInvalidPassword {
            get {
                return ResourceManager.GetString("AccountInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password retrieval question provided is invalid. Please check the value and try again..
        /// </summary>
        public static string AccountInvalidQuestion {
            get {
                return ResourceManager.GetString("AccountInvalidQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name provided is invalid. Please check the value and try again..
        /// </summary>
        public static string AccountInvalidUserName {
            get {
                return ResourceManager.GetString("AccountInvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication provider returned an error. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string AccountProviderError {
            get {
                return ResourceManager.GetString("AccountProviderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string AccountUnknownError {
            get {
                return ResourceManager.GetString("AccountUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user creation request has been canceled. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string AccountUserRejected {
            get {
                return ResourceManager.GetString("AccountUserRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums.
        /// </summary>
        public static string Albums {
            get {
                return ResourceManager.GetString("Albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account information change was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string ChangeAccountInformationErrors {
            get {
                return ResourceManager.GetString("ChangeAccountInformationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated your account details..
        /// </summary>
        public static string ChangeAccountInformationSuccess {
            get {
                return ResourceManager.GetString("ChangeAccountInformationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not requested any changes to your account. Please check your entry and try again..
        /// </summary>
        public static string ChangeAccountNoInfo {
            get {
                return ResourceManager.GetString("ChangeAccountNoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave blank unless you want to change your email address.
        /// </summary>
        public static string ChangeEmailHint {
            get {
                return ResourceManager.GetString("ChangeEmailHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string ChangePasswordConfirmPassword {
            get {
                return ResourceManager.GetString("ChangePasswordConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify your current password..
        /// </summary>
        public static string ChangePasswordCurrentMissing {
            get {
                return ResourceManager.GetString("ChangePasswordCurrentMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string ChangePasswordCurrentPassword {
            get {
                return ResourceManager.GetString("ChangePasswordCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password change was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string ChangePasswordErrors {
            get {
                return ResourceManager.GetString("ChangePasswordErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current username or password provided is incorrect or the new password is invalid..
        /// </summary>
        public static string ChangePasswordFailed {
            get {
                return ResourceManager.GetString("ChangePasswordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave blank unless you want to change your password.
        /// </summary>
        public static string ChangePasswordHint {
            get {
                return ResourceManager.GetString("ChangePasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a new password of {0} or more characters..
        /// </summary>
        public static string ChangePasswordMinLength {
            get {
                return ResourceManager.GetString("ChangePasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string ChangePasswordNewPassword {
            get {
                return ResourceManager.GetString("ChangePasswordNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify an email address..
        /// </summary>
        public static string ChangePasswordNoEmail {
            get {
                return ResourceManager.GetString("ChangePasswordNoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string ChangePasswordNoMatch {
            get {
                return ResourceManager.GetString("ChangePasswordNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a password..
        /// </summary>
        public static string ChangePasswordNoPassword {
            get {
                return ResourceManager.GetString("ChangePasswordNoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a username..
        /// </summary>
        public static string ChangePasswordNoUsername {
            get {
                return ResourceManager.GetString("ChangePasswordNoUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Theme.
        /// </summary>
        public static string ChangeTheme {
            get {
                return ResourceManager.GetString("ChangeTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confim Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred saving the track..
        /// </summary>
        public static string FavouritesFailedAdd {
            get {
                return ResourceManager.GetString("FavouritesFailedAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add this track to your favourites. It&apos;s already a favourite of yours!.
        /// </summary>
        public static string FavouritesFailedNothingAdd {
            get {
                return ResourceManager.GetString("FavouritesFailedNothingAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when trying to remove the track..
        /// </summary>
        public static string FavouritesFailedRemove {
            get {
                return ResourceManager.GetString("FavouritesFailedRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find the requested Favourite..
        /// </summary>
        public static string FavouritesFailedRemoveNotFound {
            get {
                return ResourceManager.GetString("FavouritesFailedRemoveNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve successfully added this track to your favourites!.
        /// </summary>
        public static string FavouritesSuccessAdd {
            get {
                return ResourceManager.GetString("FavouritesSuccessAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your&apos;ve successfully removed this track from your favourites!.
        /// </summary>
        public static string FavouritesSuccessRemove {
            get {
                return ResourceManager.GetString("FavouritesSuccessRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields marked {0} are required..
        /// </summary>
        public static string FormFieldsRequired {
            get {
                return ResourceManager.GetString("FormFieldsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Favourites.
        /// </summary>
        public static string ManageFavourites {
            get {
                return ResourceManager.GetString("ManageFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No music browser specified in app settings!.
        /// </summary>
        public static string MusicBrowserNotSpecified {
            get {
                return ResourceManager.GetString("MusicBrowserNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No music downloader specified in app settings!.
        /// </summary>
        public static string MusicDownloaderNotSpecified {
            get {
                return ResourceManager.GetString("MusicDownloaderNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No media player specified in app settings!.
        /// </summary>
        public static string MusicPlayerNotSpecified {
            get {
                return ResourceManager.GetString("MusicPlayerNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s account.
        /// </summary>
        public static string MyAccountHeading {
            get {
                return ResourceManager.GetString("MyAccountHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve already voted against this track!.
        /// </summary>
        public static string RatingsFailedVoteAgainst {
            get {
                return ResourceManager.GetString("RatingsFailedVoteAgainst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve successfully voted against this track!.
        /// </summary>
        public static string RatingsSuccessVoteAgainst {
            get {
                return ResourceManager.GetString("RatingsSuccessVoteAgainst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to vote against this track. Track unknown..
        /// </summary>
        public static string RatingsUnknownTracKVoteAgainst {
            get {
                return ResourceManager.GetString("RatingsUnknownTracKVoteAgainst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No username or password specified in app settings!.
        /// </summary>
        public static string SpotifyLoginEmpty {
            get {
                return ResourceManager.GetString("SpotifyLoginEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track History.
        /// </summary>
        public static string TrackHistory {
            get {
                return ResourceManager.GetString("TrackHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait....
        /// </summary>
        public static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Spoffice!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows authentication is not supported..
        /// </summary>
        public static string WindowsAuthNotSupported {
            get {
                return ResourceManager.GetString("WindowsAuthNotSupported", resourceCulture);
            }
        }
    }
}
