//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("spofficeModel", "FK_Tracks_Albums", "Albums", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Spoffice.Website.Models.Album), "Tracks", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Spoffice.Website.Models.Track))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("spofficeModel", "FK_Tracks_Artists", "Artists", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Spoffice.Website.Models.Artist), "Tracks", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Spoffice.Website.Models.Track))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("spofficeModel", "FK_Favourites_aspnet_Users", "aspnet_Users", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Spoffice.Website.Models.User), "Favourites", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Spoffice.Website.Models.Favourite))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("spofficeModel", "FK_Ratings_aspnet_Users", "aspnet_Users", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Spoffice.Website.Models.User), "Ratings", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Spoffice.Website.Models.Rating))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("spofficeModel", "FK_Favourites_Tracks", "Tracks", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Spoffice.Website.Models.Track), "Favourites", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Spoffice.Website.Models.Favourite))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("spofficeModel", "FK_Ratings_Tracks", "Tracks", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Spoffice.Website.Models.Track), "Ratings", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Spoffice.Website.Models.Rating))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("spofficeModel", "FK_TrackHistory_Tracks1", "Tracks", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Spoffice.Website.Models.Track), "TrackHistory", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Spoffice.Website.Models.TrackHistory))]

// Original file name:
// Generation date: 22/03/2010 12:27:05
namespace Spoffice.Website.Models
{
    
    /// <summary>
    /// There are no comments for spofficeEntities in the schema.
    /// </summary>
    public partial class spofficeEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new spofficeEntities object using the connection string found in the 'spofficeEntities' section of the application configuration file.
        /// </summary>
        public spofficeEntities() : 
                base("name=spofficeEntities", "spofficeEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new spofficeEntities object.
        /// </summary>
        public spofficeEntities(string connectionString) : 
                base(connectionString, "spofficeEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new spofficeEntities object.
        /// </summary>
        public spofficeEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "spofficeEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Albums in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Album> Albums
        {
            get
            {
                if ((this._Albums == null))
                {
                    this._Albums = base.CreateQuery<Album>("[Albums]");
                }
                return this._Albums;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Album> _Albums;
        /// <summary>
        /// There are no comments for Artists in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Artist> Artists
        {
            get
            {
                if ((this._Artists == null))
                {
                    this._Artists = base.CreateQuery<Artist>("[Artists]");
                }
                return this._Artists;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Artist> _Artists;
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<User> Users
        {
            get
            {
                if ((this._Users == null))
                {
                    this._Users = base.CreateQuery<User>("[Users]");
                }
                return this._Users;
            }
        }
        private global::System.Data.Objects.ObjectQuery<User> _Users;
        /// <summary>
        /// There are no comments for Favourites in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Favourite> Favourites
        {
            get
            {
                if ((this._Favourites == null))
                {
                    this._Favourites = base.CreateQuery<Favourite>("[Favourites]");
                }
                return this._Favourites;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Favourite> _Favourites;
        /// <summary>
        /// There are no comments for Ratings in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Rating> Ratings
        {
            get
            {
                if ((this._Ratings == null))
                {
                    this._Ratings = base.CreateQuery<Rating>("[Ratings]");
                }
                return this._Ratings;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Rating> _Ratings;
        /// <summary>
        /// There are no comments for TrackHistories in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<TrackHistory> TrackHistories
        {
            get
            {
                if ((this._TrackHistories == null))
                {
                    this._TrackHistories = base.CreateQuery<TrackHistory>("[TrackHistories]");
                }
                return this._TrackHistories;
            }
        }
        private global::System.Data.Objects.ObjectQuery<TrackHistory> _TrackHistories;
        /// <summary>
        /// There are no comments for Tracks in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Track> Tracks
        {
            get
            {
                if ((this._Tracks == null))
                {
                    this._Tracks = base.CreateQuery<Track>("[Tracks]");
                }
                return this._Tracks;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Track> _Tracks;
        /// <summary>
        /// There are no comments for Albums in the schema.
        /// </summary>
        public void AddToAlbums(Album album)
        {
            base.AddObject("Albums", album);
        }
        /// <summary>
        /// There are no comments for Artists in the schema.
        /// </summary>
        public void AddToArtists(Artist artist)
        {
            base.AddObject("Artists", artist);
        }
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
        /// <summary>
        /// There are no comments for Favourites in the schema.
        /// </summary>
        public void AddToFavourites(Favourite favourite)
        {
            base.AddObject("Favourites", favourite);
        }
        /// <summary>
        /// There are no comments for Ratings in the schema.
        /// </summary>
        public void AddToRatings(Rating rating)
        {
            base.AddObject("Ratings", rating);
        }
        /// <summary>
        /// There are no comments for TrackHistories in the schema.
        /// </summary>
        public void AddToTrackHistories(TrackHistory trackHistory)
        {
            base.AddObject("TrackHistories", trackHistory);
        }
        /// <summary>
        /// There are no comments for Tracks in the schema.
        /// </summary>
        public void AddToTracks(Track track)
        {
            base.AddObject("Tracks", track);
        }
        /// <summary>
        /// There are no comments for spofficeModel.GetTracksToPlay in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectResult<Track> GetTracksToPlay(global::System.Nullable<int> amount, string exclude)
        {
            global::System.Data.Objects.ObjectParameter amountParameter;
            if (amount.HasValue)
            {
                amountParameter = new global::System.Data.Objects.ObjectParameter("amount", amount);
            }
            else
            {
                amountParameter = new global::System.Data.Objects.ObjectParameter("amount", typeof(int));
            }
            global::System.Data.Objects.ObjectParameter excludeParameter;
            if ((exclude != null))
            {
                excludeParameter = new global::System.Data.Objects.ObjectParameter("exclude", exclude);
            }
            else
            {
                excludeParameter = new global::System.Data.Objects.ObjectParameter("exclude", typeof(string));
            }
            return base.ExecuteFunction<Track>("GetTracksToPlay", amountParameter, excludeParameter);
        }
    }
    /// <summary>
    /// There are no comments for spofficeModel.Album in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="spofficeModel", Name="Album")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Album : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Album object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        public static Album CreateAlbum(global::System.Guid id, string name)
        {
            Album album = new Album();
            album.Id = id;
            album.Name = name;
            return album;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Released in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> Released
        {
            get
            {
                return this._Released;
            }
            set
            {
                this.OnReleasedChanging(value);
                this.ReportPropertyChanging("Released");
                this._Released = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Released");
                this.OnReleasedChanged();
            }
        }
        private global::System.Nullable<int> _Released;
        partial void OnReleasedChanging(global::System.Nullable<int> value);
        partial void OnReleasedChanged();
        /// <summary>
        /// There are no comments for Property MusicBrainzId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.Guid> MusicBrainzId
        {
            get
            {
                return this._MusicBrainzId;
            }
            set
            {
                this.OnMusicBrainzIdChanging(value);
                this.ReportPropertyChanging("MusicBrainzId");
                this._MusicBrainzId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MusicBrainzId");
                this.OnMusicBrainzIdChanged();
            }
        }
        private global::System.Nullable<global::System.Guid> _MusicBrainzId;
        partial void OnMusicBrainzIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnMusicBrainzIdChanged();
        /// <summary>
        /// There are no comments for Tracks in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("spofficeModel", "FK_Tracks_Albums", "Tracks")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Track> Tracks
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Track>("spofficeModel.FK_Tracks_Albums", "Tracks");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Track>("spofficeModel.FK_Tracks_Albums", "Tracks", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for spofficeModel.Artist in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="spofficeModel", Name="Artist")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Artist : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Artist object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        public static Artist CreateArtist(global::System.Guid id, string name)
        {
            Artist artist = new Artist();
            artist.Id = id;
            artist.Name = name;
            return artist;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property MusicBrainzId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.Guid> MusicBrainzId
        {
            get
            {
                return this._MusicBrainzId;
            }
            set
            {
                this.OnMusicBrainzIdChanging(value);
                this.ReportPropertyChanging("MusicBrainzId");
                this._MusicBrainzId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MusicBrainzId");
                this.OnMusicBrainzIdChanged();
            }
        }
        private global::System.Nullable<global::System.Guid> _MusicBrainzId;
        partial void OnMusicBrainzIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnMusicBrainzIdChanged();
        /// <summary>
        /// There are no comments for Tracks in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("spofficeModel", "FK_Tracks_Artists", "Tracks")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Track> Tracks
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Track>("spofficeModel.FK_Tracks_Artists", "Tracks");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Track>("spofficeModel.FK_Tracks_Artists", "Tracks", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for spofficeModel.User in the schema.
    /// </summary>
    /// <KeyProperties>
    /// UserId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="spofficeModel", Name="User")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class User : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="applicationId">Initial value of ApplicationId.</param>
        /// <param name="userId">Initial value of UserId.</param>
        /// <param name="userName">Initial value of UserName.</param>
        /// <param name="loweredUserName">Initial value of LoweredUserName.</param>
        /// <param name="isAnonymous">Initial value of IsAnonymous.</param>
        /// <param name="lastActivityDate">Initial value of LastActivityDate.</param>
        public static User CreateUser(global::System.Guid applicationId, global::System.Guid userId, string userName, string loweredUserName, bool isAnonymous, global::System.DateTime lastActivityDate)
        {
            User user = new User();
            user.ApplicationId = applicationId;
            user.UserId = userId;
            user.UserName = userName;
            user.LoweredUserName = loweredUserName;
            user.IsAnonymous = isAnonymous;
            user.LastActivityDate = lastActivityDate;
            return user;
        }
        /// <summary>
        /// There are no comments for Property ApplicationId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid ApplicationId
        {
            get
            {
                return this._ApplicationId;
            }
            set
            {
                this.OnApplicationIdChanging(value);
                this.ReportPropertyChanging("ApplicationId");
                this._ApplicationId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ApplicationId");
                this.OnApplicationIdChanged();
            }
        }
        private global::System.Guid _ApplicationId;
        partial void OnApplicationIdChanging(global::System.Guid value);
        partial void OnApplicationIdChanged();
        /// <summary>
        /// There are no comments for Property UserId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid UserId
        {
            get
            {
                return this._UserId;
            }
            set
            {
                this.OnUserIdChanging(value);
                this.ReportPropertyChanging("UserId");
                this._UserId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("UserId");
                this.OnUserIdChanged();
            }
        }
        private global::System.Guid _UserId;
        partial void OnUserIdChanging(global::System.Guid value);
        partial void OnUserIdChanged();
        /// <summary>
        /// There are no comments for Property UserName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this._UserName;
            }
            set
            {
                this.OnUserNameChanging(value);
                this.ReportPropertyChanging("UserName");
                this._UserName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("UserName");
                this.OnUserNameChanged();
            }
        }
        private string _UserName;
        partial void OnUserNameChanging(string value);
        partial void OnUserNameChanged();
        /// <summary>
        /// There are no comments for Property LoweredUserName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string LoweredUserName
        {
            get
            {
                return this._LoweredUserName;
            }
            set
            {
                this.OnLoweredUserNameChanging(value);
                this.ReportPropertyChanging("LoweredUserName");
                this._LoweredUserName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("LoweredUserName");
                this.OnLoweredUserNameChanged();
            }
        }
        private string _LoweredUserName;
        partial void OnLoweredUserNameChanging(string value);
        partial void OnLoweredUserNameChanged();
        /// <summary>
        /// There are no comments for Property MobileAlias in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileAlias
        {
            get
            {
                return this._MobileAlias;
            }
            set
            {
                this.OnMobileAliasChanging(value);
                this.ReportPropertyChanging("MobileAlias");
                this._MobileAlias = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("MobileAlias");
                this.OnMobileAliasChanged();
            }
        }
        private string _MobileAlias;
        partial void OnMobileAliasChanging(string value);
        partial void OnMobileAliasChanged();
        /// <summary>
        /// There are no comments for Property IsAnonymous in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAnonymous
        {
            get
            {
                return this._IsAnonymous;
            }
            set
            {
                this.OnIsAnonymousChanging(value);
                this.ReportPropertyChanging("IsAnonymous");
                this._IsAnonymous = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IsAnonymous");
                this.OnIsAnonymousChanged();
            }
        }
        private bool _IsAnonymous;
        partial void OnIsAnonymousChanging(bool value);
        partial void OnIsAnonymousChanged();
        /// <summary>
        /// There are no comments for Property LastActivityDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime LastActivityDate
        {
            get
            {
                return this._LastActivityDate;
            }
            set
            {
                this.OnLastActivityDateChanging(value);
                this.ReportPropertyChanging("LastActivityDate");
                this._LastActivityDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LastActivityDate");
                this.OnLastActivityDateChanged();
            }
        }
        private global::System.DateTime _LastActivityDate;
        partial void OnLastActivityDateChanging(global::System.DateTime value);
        partial void OnLastActivityDateChanged();
        /// <summary>
        /// There are no comments for Favourites in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("spofficeModel", "FK_Favourites_aspnet_Users", "Favourites")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Favourite> Favourites
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Favourite>("spofficeModel.FK_Favourites_aspnet_Users", "Favourites");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Favourite>("spofficeModel.FK_Favourites_aspnet_Users", "Favourites", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Ratings in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("spofficeModel", "FK_Ratings_aspnet_Users", "Ratings")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Rating> Ratings
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Rating>("spofficeModel.FK_Ratings_aspnet_Users", "Ratings");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Rating>("spofficeModel.FK_Ratings_aspnet_Users", "Ratings", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for spofficeModel.Favourite in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="spofficeModel", Name="Favourite")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Favourite : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Favourite object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        public static Favourite CreateFavourite(int id)
        {
            Favourite favourite = new Favourite();
            favourite.Id = id;
            return favourite;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("spofficeModel", "FK_Favourites_aspnet_Users", "aspnet_Users")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public User User
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("spofficeModel.FK_Favourites_aspnet_Users", "aspnet_Users").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("spofficeModel.FK_Favourites_aspnet_Users", "aspnet_Users").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<User> UserReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("spofficeModel.FK_Favourites_aspnet_Users", "aspnet_Users");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<User>("spofficeModel.FK_Favourites_aspnet_Users", "aspnet_Users", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Track in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("spofficeModel", "FK_Favourites_Tracks", "Tracks")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Track Track
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Track>("spofficeModel.FK_Favourites_Tracks", "Tracks").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Track>("spofficeModel.FK_Favourites_Tracks", "Tracks").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Track in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Track> TrackReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Track>("spofficeModel.FK_Favourites_Tracks", "Tracks");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Track>("spofficeModel.FK_Favourites_Tracks", "Tracks", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for spofficeModel.Rating in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="spofficeModel", Name="Rating")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Rating : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Rating object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="value">Initial value of Value.</param>
        public static Rating CreateRating(int id, int value)
        {
            Rating rating = new Rating();
            rating.Id = id;
            rating.Value = value;
            return rating;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Value in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                this.OnValueChanging(value);
                this.ReportPropertyChanging("Value");
                this._Value = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Value");
                this.OnValueChanged();
            }
        }
        private int _Value;
        partial void OnValueChanging(int value);
        partial void OnValueChanged();
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("spofficeModel", "FK_Ratings_aspnet_Users", "aspnet_Users")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public User User
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("spofficeModel.FK_Ratings_aspnet_Users", "aspnet_Users").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("spofficeModel.FK_Ratings_aspnet_Users", "aspnet_Users").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<User> UserReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("spofficeModel.FK_Ratings_aspnet_Users", "aspnet_Users");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<User>("spofficeModel.FK_Ratings_aspnet_Users", "aspnet_Users", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Track in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("spofficeModel", "FK_Ratings_Tracks", "Tracks")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Track Track
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Track>("spofficeModel.FK_Ratings_Tracks", "Tracks").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Track>("spofficeModel.FK_Ratings_Tracks", "Tracks").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Track in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Track> TrackReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Track>("spofficeModel.FK_Ratings_Tracks", "Tracks");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Track>("spofficeModel.FK_Ratings_Tracks", "Tracks", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for spofficeModel.TrackHistory in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="spofficeModel", Name="TrackHistory")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class TrackHistory : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new TrackHistory object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="datetime">Initial value of Datetime.</param>
        public static TrackHistory CreateTrackHistory(int id, global::System.DateTime datetime)
        {
            TrackHistory trackHistory = new TrackHistory();
            trackHistory.Id = id;
            trackHistory.Datetime = datetime;
            return trackHistory;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Datetime in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime Datetime
        {
            get
            {
                return this._Datetime;
            }
            set
            {
                this.OnDatetimeChanging(value);
                this.ReportPropertyChanging("Datetime");
                this._Datetime = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Datetime");
                this.OnDatetimeChanged();
            }
        }
        private global::System.DateTime _Datetime;
        partial void OnDatetimeChanging(global::System.DateTime value);
        partial void OnDatetimeChanged();
        /// <summary>
        /// There are no comments for Track in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("spofficeModel", "FK_TrackHistory_Tracks1", "Tracks")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Track Track
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Track>("spofficeModel.FK_TrackHistory_Tracks1", "Tracks").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Track>("spofficeModel.FK_TrackHistory_Tracks1", "Tracks").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Track in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Track> TrackReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Track>("spofficeModel.FK_TrackHistory_Tracks1", "Tracks");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Track>("spofficeModel.FK_TrackHistory_Tracks1", "Tracks", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for spofficeModel.Track in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="spofficeModel", Name="Track")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Track : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Track object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="title">Initial value of Title.</param>
        /// <param name="length">Initial value of Length.</param>
        public static Track CreateTrack(global::System.Guid id, string title, int length)
        {
            Track track = new Track();
            track.Id = id;
            track.Title = title;
            track.Length = length;
            return track;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this.ReportPropertyChanging("Title");
                this._Title = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Title");
                this.OnTitleChanged();
            }
        }
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Length in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Length
        {
            get
            {
                return this._Length;
            }
            set
            {
                this.OnLengthChanging(value);
                this.ReportPropertyChanging("Length");
                this._Length = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Length");
                this.OnLengthChanged();
            }
        }
        private int _Length;
        partial void OnLengthChanging(int value);
        partial void OnLengthChanged();
        /// <summary>
        /// There are no comments for Property MusicBrainzId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.Guid> MusicBrainzId
        {
            get
            {
                return this._MusicBrainzId;
            }
            set
            {
                this.OnMusicBrainzIdChanging(value);
                this.ReportPropertyChanging("MusicBrainzId");
                this._MusicBrainzId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MusicBrainzId");
                this.OnMusicBrainzIdChanged();
            }
        }
        private global::System.Nullable<global::System.Guid> _MusicBrainzId;
        partial void OnMusicBrainzIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnMusicBrainzIdChanged();
        /// <summary>
        /// There are no comments for Album in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("spofficeModel", "FK_Tracks_Albums", "Albums")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Album Album
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Album>("spofficeModel.FK_Tracks_Albums", "Albums").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Album>("spofficeModel.FK_Tracks_Albums", "Albums").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Album in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Album> AlbumReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Album>("spofficeModel.FK_Tracks_Albums", "Albums");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Album>("spofficeModel.FK_Tracks_Albums", "Albums", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Artist in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("spofficeModel", "FK_Tracks_Artists", "Artists")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Artist Artist
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Artist>("spofficeModel.FK_Tracks_Artists", "Artists").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Artist>("spofficeModel.FK_Tracks_Artists", "Artists").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Artist in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Artist> ArtistReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Artist>("spofficeModel.FK_Tracks_Artists", "Artists");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Artist>("spofficeModel.FK_Tracks_Artists", "Artists", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Favourites in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("spofficeModel", "FK_Favourites_Tracks", "Favourites")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Favourite> Favourites
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Favourite>("spofficeModel.FK_Favourites_Tracks", "Favourites");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Favourite>("spofficeModel.FK_Favourites_Tracks", "Favourites", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Ratings in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("spofficeModel", "FK_Ratings_Tracks", "Ratings")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Rating> Ratings
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Rating>("spofficeModel.FK_Ratings_Tracks", "Ratings");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Rating>("spofficeModel.FK_Ratings_Tracks", "Ratings", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for TrackHistory in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("spofficeModel", "FK_TrackHistory_Tracks1", "TrackHistory")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<TrackHistory> TrackHistory
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<TrackHistory>("spofficeModel.FK_TrackHistory_Tracks1", "TrackHistory");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<TrackHistory>("spofficeModel.FK_TrackHistory_Tracks1", "TrackHistory", value);
                }
            }
        }
    }
}
